apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-bcop
  namespace: service
spec:
  serviceName: proxy-bcop
  selector:
    matchLabels:
      app: proxy-bcop
  template:
    metadata:
      labels:
        app: proxy-bcop
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/hiroyaonoe/bcop-proxy/bcop-proxy:latest"
          command: ['/bin/bcop-proxy', '--proxy-port', '80', '--admin-port', '9000', '--default-addr', 'service-bcop-main.service.svc.cluster.local:80', '--propagate=true', '--controller-url', 'http://proxy-controller.bcop-system.svc.cluster.local:8080', '--id', 'service-bcop']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 80
            - name: admin
              containerPort: 9000
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcrcred

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-bcop
  namespace: service
spec:
  type: NodePort
  selector:
    app: proxy-bcop
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
