apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-$(PROTO)-$(ENV)
  labels:
    env: $(ENV)
spec:
  selector:
    matchLabels:
      app: service-$(PROTO)-$(ENV)
  template:
    metadata:
      labels:
        app: service-$(PROTO)-$(ENV)
    spec:
      containers:
        - name: service
          image: nginx:1.23.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: service-$(PROTO)-$(ENV)
spec:
  type: NodePort
  selector:
    app: service-$(PROTO)-$(ENV)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
