apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-picop
  namespace: service
spec:
  selector:
    matchLabels:
      app: proxy-picop
  template:
    metadata:
      labels:
        app: proxy-picop
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '80', '--admin-port', '9000', '--default-addr', 'service-picop-main.service.svc.cluster.local:80', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'service-picop']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 80
            - name: admin
              containerPort: 9000
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-picop
  namespace: service
spec:
  type: NodePort
  selector:
    app: proxy-picop
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
