apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-http
  namespace: service-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-http
  template:
    metadata:
      labels:
        app: proxy-http
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '80', '--admin-port', '9000', '--default-addr', 'service-http-main.service.svc.cluster.local:80', '--propagate=false', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'service-http']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 80
            - name: admin
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-http
  namespace: service-proxy
spec:
  type: NodePort
  selector:
    app: proxy-http
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32101
