apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-http-main
  namespace: service
  labels:
    env: main
spec:
  selector:
    matchLabels:
      app: service-http-main
  template:
    metadata:
      labels:
        app: service-http-main
    spec:
      containers:
        - name: service
          image: nginx:1.23.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap: 
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: service-http-main
  namespace: service
spec:
  type: NodePort
  selector:
    app: service-http-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
