apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-http-main
  namespace: service-istio
  labels:
    env: main
spec:
  selector:
    matchLabels:
      app: service-http-main
  template:
    metadata:
      labels:
        app: service-http-main
      annotations:
        sidecar.istio.io/proxyCPU: "100m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/proxyCPULimit: "16"
        sidecar.istio.io/proxyMemoryLimit: "16Gi"
    spec:
      containers:
        - name: service
          image: nginx:1.23.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap: 
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: service-http-main
  namespace: service-istio
spec:
  type: NodePort
  selector:
    app: service-http-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: service
    # - protocol: TCP
    #   port: 15006
    #   nodePort: 32002
    #   name: istio
