name: docker

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push benchmark/service-picop"
        uses: docker/build-push-action@v3
        with:
          context: ./service-picop
          push: true
          tags: ghcr.io/picop-rd/benchmark/service-picop:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Build and push benchmark/service-http"
        uses: docker/build-push-action@v3
        with:
          context: ./service-http
          push: true
          tags: ghcr.io/picop-rd/benchmark/service-http:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
